name: clebarr

services:
  clebarr:
    build:
      context: .
      dockerfile: Dockerfile
    image: clebarr:latest
    container_name: clebarr
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./config:/app/config
    environment:
      - PLEX_TOKEN=${PLEX_TOKEN}
      - PLEX_SERVER_URL=${PLEX_SERVER_URL:-http://localhost:32400}
      - ENV=development
      - LOG_LEVEL=DEBUG
    restart: unless-stopped 